from typing import Protocol
from datetime import datetime


class Transaction(Protocol):
    async def get_credit(self) -> tuple[str, float]: ...
    async def get_debit(self) -> tuple[str, float]: ...
    async def get_date(self) -> datetime: ...


class Account(Protocol):
    async def get_name(self) -> str: ...
    async def get_transactions(self) -> list[Transaction]: ...


class LedgerFile(Protocol):
    async def get_accounts_names(self) -> list[str]: ...
    async def get_accounts(self) -> list[Account]: ...
    async def get_account(self, acct_name: str) -> Account: ...
