from pathlib import Path
from typing import Literal, Protocol, Self
from datetime import date, datetime

type HLEDGER_STD_REPORTS = Literal[
    "print",
    "aregister",
    "register",
    "balancesheet",
    "balancesheetequity",
    "cashflow",
    "incomestatement",
]

type HLEDGER_BASIC_REPORTS = Literal["accounts", "commodities", "files"]
type HLEDGER_OUTPUTS = Literal["csv", "json"]


class Transaction(Protocol):
    async def get_credit(self) -> tuple[str, float]: ...
    async def get_debit(self) -> tuple[str, float]: ...
    async def get_date(self) -> datetime: ...


class Account(Protocol):
    async def get_name(self) -> str: ...
    async def get_transactions(self) -> list[Transaction]: ...


class LedgerFile(Protocol):
    async def get_accounts(self) -> list[Account]: ...
    async def get_account(self, acct_name: str) -> Account: ...


class HledgerCommand(Protocol):
    async def execute(self) -> tuple[bytes, bytes]: ...


class HledgerCommandBuilder(Protocol):
    def with_binary(self, path_to_binary: str) -> Self: ...
    def with_file(self, path: str) -> Self: ...
    def with_std_report(self, report: HLEDGER_STD_REPORTS) -> Self: ...
    def with_basic_report(self, report: HLEDGER_BASIC_REPORTS) -> Self: ...
    def with_start_date(self, start_date: date) -> Self: ...
    def with_end_date(self, end_date: date) -> Self: ...
    def with_account(self, account: str) -> Self: ...
    def with_output(self, output: HLEDGER_OUTPUTS) -> Self: ...
    def build(self) -> HledgerCommand: ...
